spring:
  main:
    banner-mode: off
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: localhost
            password: abcdefg
          keystore:
            type: PKCS12
            location: classpath:keystore.p12
            password: abcdefg
        client:
          truststore:
            type: PKCS12
            location: classpath:truststore.p12
            password: abcdefg
server:
  ssl:
    bundle: server
logging:
  level:
    root: off
